[phases.setup]
  nixpkgsArchive = "51ad838b03a05b1de6f9f2a0fffecee64a9788ee" 
cache = false  

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build:client", "npx tsc -p tsconfig.server.json"]

[start]
cmd = "node dist/server/index.js"
