// @ts-nocheck
// Phase 3 — Academy Layer: External Course Seeds
// Curated courses from Coursera, FreeCodeCamp, Udemy, and other platforms

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const externalCourses = [
  // ===== COURSERA COURSES =====
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'google-it-support',
    title: 'Google IT Support Professional Certificate',
    description: 'Earn a career certificate in IT support, one of the world\'s fastest-growing jobs. Learn practical skills including networking, operating systems, and security.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-it-support',
    instructor: 'Google',
    institution: 'Google',
    duration: 18000, // ~300 hours
    category: 'Technology',
    subcategory: 'IT Support',
    difficulty: 'Beginner',
    tags: ['IT', 'Technical Support', 'Networking', 'Security'],
    price: 49,
    rating: 4.8,
    reviewCount: 125000,
    enrollmentCount: 500000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 150,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'ibm-data-science',
    title: 'IBM Data Science Professional Certificate',
    description: 'Learn data science from scratch. Master Python, SQL, and machine learning. Build real-world projects and earn an industry-recognized credential.',
    courseUrl: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    instructor: 'IBM',
    institution: 'IBM',
    duration: 21600, // ~360 hours
    category: 'Data Science',
    subcategory: 'Machine Learning',
    difficulty: 'Beginner',
    tags: ['Python', 'Data Science', 'Machine Learning', 'SQL', 'Visualization'],
    price: 49,
    rating: 4.7,
    reviewCount: 98000,
    enrollmentCount: 420000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 200,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'meta-front-end-developer',
    title: 'Meta Front-End Developer Professional Certificate',
    description: 'Launch your career as a front-end developer. Learn HTML, CSS, JavaScript, React, and UI/UX design principles.',
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    instructor: 'Meta',
    institution: 'Meta',
    duration: 25200, // ~420 hours
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Beginner',
    tags: ['HTML', 'CSS', 'JavaScript', 'React', 'UI/UX'],
    price: 49,
    rating: 4.8,
    reviewCount: 75000,
    enrollmentCount: 350000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 180,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'google-digital-marketing',
    title: 'Google Digital Marketing & E-commerce Professional Certificate',
    description: 'Get trained in digital marketing and e-commerce. Learn SEO, SEM, email marketing, analytics, and how to sell products online.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    instructor: 'Google',
    institution: 'Google',
    duration: 15000, // ~250 hours
    category: 'Business',
    subcategory: 'Digital Marketing',
    difficulty: 'Beginner',
    tags: ['Digital Marketing', 'SEO', 'E-commerce', 'Analytics', 'Social Media'],
    price: 49,
    rating: 4.7,
    reviewCount: 65000,
    enrollmentCount: 280000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 120,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'deeplearning-ai-machine-learning',
    title: 'Machine Learning Specialization',
    description: 'Learn Machine Learning from Andrew Ng. Master foundational algorithms, neural networks, and how to build AI systems.',
    courseUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    instructor: 'Andrew Ng',
    institution: 'Stanford University',
    duration: 18000, // ~300 hours
    category: 'Data Science',
    subcategory: 'Machine Learning',
    difficulty: 'Intermediate',
    tags: ['Machine Learning', 'AI', 'Deep Learning', 'Python', 'Neural Networks'],
    price: 49,
    rating: 4.9,
    reviewCount: 150000,
    enrollmentCount: 650000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 8,
    workContractCount: 250,
    hasCertificate: true,
    certificateType: 'Specialization',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'google-project-management',
    title: 'Google Project Management Professional Certificate',
    description: 'Learn project management fundamentals. Master Agile, Scrum, and practical project planning skills.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-project-management',
    instructor: 'Google',
    institution: 'Google',
    duration: 15600, // ~260 hours
    category: 'Business',
    subcategory: 'Project Management',
    difficulty: 'Beginner',
    tags: ['Project Management', 'Agile', 'Scrum', 'Planning'],
    price: 49,
    rating: 4.8,
    reviewCount: 95000,
    enrollmentCount: 400000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 140,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'google-ux-design',
    title: 'Google UX Design Professional Certificate',
    description: 'Learn UX design fundamentals. Master user research, wireframing, prototyping, and Figma.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-ux-design',
    instructor: 'Google',
    institution: 'Google',
    duration: 17400, // ~290 hours
    category: 'Design',
    subcategory: 'UX Design',
    difficulty: 'Beginner',
    tags: ['UX Design', 'User Research', 'Figma', 'Prototyping', 'Wireframing'],
    price: 49,
    rating: 4.7,
    reviewCount: 55000,
    enrollmentCount: 220000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 8,
    workContractCount: 95,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },
  {
    tenantId: 'system',
    platform: 'COURSERA' as const,
    externalId: 'google-cybersecurity',
    title: 'Google Cybersecurity Professional Certificate',
    description: 'Start a career in cybersecurity. Learn security foundations, Python, SIEM, and how to protect systems.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    instructor: 'Google',
    institution: 'Google',
    duration: 18000, // ~300 hours
    category: 'Technology',
    subcategory: 'Cybersecurity',
    difficulty: 'Beginner',
    tags: ['Cybersecurity', 'Security', 'Python', 'SIEM', 'Networking'],
    price: 49,
    rating: 4.8,
    reviewCount: 45000,
    enrollmentCount: 180000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 110,
    hasCertificate: true,
    certificateType: 'Professional Certificate',
  },

  // ===== FREECODECAMP COURSES =====
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'responsive-web-design',
    title: 'Responsive Web Design Certification',
    description: 'Learn HTML5, CSS3, Responsive Design, Accessibility, CSS Flexbox and Grid. Build 5 projects to earn certification.',
    courseUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Beginner',
    tags: ['HTML', 'CSS', 'Responsive Design', 'Flexbox', 'Grid', 'Accessibility'],
    price: 0,
    rating: 4.9,
    reviewCount: 50000,
    enrollmentCount: 200000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 85,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'javascript-algorithms',
    title: 'JavaScript Algorithms and Data Structures Certification',
    description: 'Master JavaScript fundamentals, algorithms, OOP, and functional programming. Build 5 projects.',
    courseUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Intermediate',
    tags: ['JavaScript', 'Algorithms', 'Data Structures', 'OOP', 'Functional Programming'],
    price: 0,
    rating: 4.9,
    reviewCount: 48000,
    enrollmentCount: 180000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 120,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'front-end-libraries',
    title: 'Front End Development Libraries Certification',
    description: 'Learn Bootstrap, jQuery, Sass, React, Redux. Build 5 projects using modern libraries.',
    courseUrl: 'https://www.freecodecamp.org/learn/front-end-development-libraries/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    tags: ['React', 'Redux', 'Bootstrap', 'jQuery', 'Sass'],
    price: 0,
    rating: 4.8,
    reviewCount: 35000,
    enrollmentCount: 120000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 95,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'back-end-apis',
    title: 'Back End Development and APIs Certification',
    description: 'Learn Node.js, Express, MongoDB, Mongoose. Build REST APIs and full-stack applications.',
    courseUrl: 'https://www.freecodecamp.org/learn/back-end-development-and-apis/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Technology',
    subcategory: 'Backend Development',
    difficulty: 'Intermediate',
    tags: ['Node.js', 'Express', 'MongoDB', 'REST APIs', 'JavaScript'],
    price: 0,
    rating: 4.8,
    reviewCount: 30000,
    enrollmentCount: 100000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 90,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'data-analysis-python',
    title: 'Data Analysis with Python Certification',
    description: 'Learn NumPy, Pandas, Matplotlib, Seaborn. Analyze data and create visualizations with Python.',
    courseUrl: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Data Science',
    subcategory: 'Data Analysis',
    difficulty: 'Intermediate',
    tags: ['Python', 'NumPy', 'Pandas', 'Data Analysis', 'Visualization'],
    price: 0,
    rating: 4.7,
    reviewCount: 25000,
    enrollmentCount: 80000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 75,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'FREECODECAMP' as const,
    externalId: 'machine-learning-python',
    title: 'Machine Learning with Python Certification',
    description: 'Learn machine learning fundamentals with TensorFlow, Keras, and scikit-learn. Build AI projects.',
    courseUrl: 'https://www.freecodecamp.org/learn/machine-learning-with-python/',
    instructor: 'FreeCodeCamp',
    institution: 'FreeCodeCamp',
    duration: 18000, // 300 hours
    category: 'Data Science',
    subcategory: 'Machine Learning',
    difficulty: 'Advanced',
    tags: ['Machine Learning', 'Python', 'TensorFlow', 'Keras', 'AI'],
    price: 0,
    rating: 4.8,
    reviewCount: 20000,
    enrollmentCount: 60000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 8,
    workContractCount: 85,
    hasCertificate: true,
    certificateType: 'Certification',
  },

  // ===== UDEMY COURSES =====
  {
    tenantId: 'system',
    platform: 'UDEMY' as const,
    externalId: '100-days-code',
    title: '100 Days of Code: The Complete Python Pro Bootcamp',
    description: 'Master Python by building 100 projects in 100 days. Build websites, games, apps, and more.',
    courseUrl: 'https://www.udemy.com/course/100-days-of-code/',
    instructor: 'Dr. Angela Yu',
    institution: 'London App Brewery',
    duration: 18600, // 310 hours
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    tags: ['Python', 'Web Development', 'Data Science', 'GUI', 'Automation'],
    price: 14.99, // Often on sale for $14.99
    rating: 4.8,
    reviewCount: 180000,
    enrollmentCount: 800000,
    isVerified: false,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 110,
    hasCertificate: true,
    certificateType: 'Completion Certificate',
  },
  {
    tenantId: 'system',
    platform: 'UDEMY' as const,
    externalId: 'react-complete-guide',
    title: 'React - The Complete Guide',
    description: 'Dive deep into React 18 with hooks, Redux, Next.js, TypeScript, and more. Build enterprise apps.',
    courseUrl: 'https://www.udemy.com/course/react-the-complete-guide/',
    instructor: 'Maximilian Schwarzmüller',
    institution: 'Academind',
    duration: 16800, // 280 hours
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    tags: ['React', 'Redux', 'TypeScript', 'Next.js', 'Hooks'],
    price: 14.99,
    rating: 4.7,
    reviewCount: 120000,
    enrollmentCount: 450000,
    isVerified: false,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 95,
    hasCertificate: true,
    certificateType: 'Completion Certificate',
  },

  // ===== HUBSPOT ACADEMY =====
  {
    tenantId: 'system',
    platform: 'HUBSPOT' as const,
    externalId: 'inbound-marketing',
    title: 'Inbound Marketing Certification',
    description: 'Master inbound marketing methodology. Learn content creation, SEO, social promotion, and email marketing.',
    courseUrl: 'https://academy.hubspot.com/courses/inbound-marketing',
    instructor: 'HubSpot Academy',
    institution: 'HubSpot',
    duration: 360, // 6 hours
    category: 'Business',
    subcategory: 'Digital Marketing',
    difficulty: 'Beginner',
    tags: ['Inbound Marketing', 'Content Marketing', 'SEO', 'Email Marketing', 'Social Media'],
    price: 0,
    rating: 4.8,
    reviewCount: 30000,
    enrollmentCount: 150000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 60,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'HUBSPOT' as const,
    externalId: 'content-marketing',
    title: 'Content Marketing Certification',
    description: 'Learn to create compelling content that attracts and converts. Master blogging, video, and distribution.',
    courseUrl: 'https://academy.hubspot.com/courses/content-marketing',
    instructor: 'HubSpot Academy',
    institution: 'HubSpot',
    duration: 420, // 7 hours
    category: 'Business',
    subcategory: 'Content Marketing',
    difficulty: 'Beginner',
    tags: ['Content Marketing', 'Blogging', 'Video Marketing', 'Strategy'],
    price: 0,
    rating: 4.7,
    reviewCount: 25000,
    enrollmentCount: 120000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 45,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'HUBSPOT' as const,
    externalId: 'seo-training',
    title: 'SEO Training Certification',
    description: 'Master search engine optimization. Learn on-page, off-page SEO, and link building strategies.',
    courseUrl: 'https://academy.hubspot.com/courses/seo-training',
    instructor: 'HubSpot Academy',
    institution: 'HubSpot',
    duration: 480, // 8 hours
    category: 'Business',
    subcategory: 'SEO',
    difficulty: 'Intermediate',
    tags: ['SEO', 'Search Engine Optimization', 'Link Building', 'Keywords'],
    price: 0,
    rating: 4.6,
    reviewCount: 20000,
    enrollmentCount: 90000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 55,
    hasCertificate: true,
    certificateType: 'Certification',
  },

  // ===== GOOGLE SKILLSHOP =====
  {
    tenantId: 'system',
    platform: 'GOOGLE_SKILLSHOP' as const,
    externalId: 'google-analytics',
    title: 'Google Analytics Certification',
    description: 'Master Google Analytics 4. Learn to measure, analyze, and optimize digital marketing performance.',
    courseUrl: 'https://skillshop.withgoogle.com/category/analytics',
    instructor: 'Google',
    institution: 'Google',
    duration: 600, // 10 hours
    category: 'Data Science',
    subcategory: 'Analytics',
    difficulty: 'Intermediate',
    tags: ['Google Analytics', 'GA4', 'Data Analysis', 'Digital Marketing'],
    price: 0,
    rating: 4.8,
    reviewCount: 80000,
    enrollmentCount: 300000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 80,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'GOOGLE_SKILLSHOP' as const,
    externalId: 'google-ads-search',
    title: 'Google Ads Search Certification',
    description: 'Master Google Search Ads. Learn keyword research, bidding, ad copy, and campaign optimization.',
    courseUrl: 'https://skillshop.withgoogle.com/category/ads',
    instructor: 'Google',
    institution: 'Google',
    duration: 480, // 8 hours
    category: 'Business',
    subcategory: 'Digital Advertising',
    difficulty: 'Intermediate',
    tags: ['Google Ads', 'PPC', 'Search Advertising', 'Campaign Management'],
    price: 0,
    rating: 4.7,
    reviewCount: 60000,
    enrollmentCount: 250000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 70,
    hasCertificate: true,
    certificateType: 'Certification',
  },

  // ===== UNIATHENA COURSES =====
  {
    tenantId: 'system',
    platform: 'UNIATHENA' as const,
    externalId: 'mba-general',
    title: 'MBA in General Management',
    description: 'Earn an accredited MBA. Master strategic management, leadership, finance, and entrepreneurship.',
    courseUrl: 'https://www.uniathena.com/mba-in-general-management',
    instructor: 'UniAthena',
    institution: 'UniAthena / University of Wales Trinity Saint David',
    duration: 15600, // 12 months
    category: 'Business',
    subcategory: 'MBA',
    difficulty: 'Advanced',
    tags: ['MBA', 'Management', 'Leadership', 'Strategy', 'Entrepreneurship'],
    price: 2500,
    rating: 4.5,
    reviewCount: 2000,
    enrollmentCount: 8000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 200,
    hasCertificate: true,
    certificateType: 'MBA Degree',
  },
  {
    tenantId: 'system',
    platform: 'UNIATHENA' as const,
    externalId: 'diploma-digital-marketing',
    title: 'Diploma in Digital Marketing',
    description: 'Comprehensive digital marketing diploma. Learn SEO, social media, content marketing, and analytics.',
    courseUrl: 'https://www.uniathena.com/diploma-in-digital-marketing',
    instructor: 'UniAthena',
    institution: 'UniAthena',
    duration: 7200, // 6 months
    category: 'Business',
    subcategory: 'Digital Marketing',
    difficulty: 'Intermediate',
    tags: ['Digital Marketing', 'SEO', 'Social Media', 'Content Marketing', 'Analytics'],
    price: 350,
    rating: 4.6,
    reviewCount: 1500,
    enrollmentCount: 5000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 50,
    hasCertificate: true,
    certificateType: 'Diploma',
  },
  {
    tenantId: 'system',
    platform: 'UNIATHENA' as const,
    externalId: 'certificate-entrepreneurship',
    title: 'Certificate in Entrepreneurship',
    description: 'Short entrepreneurship program. Learn business planning, funding, and startup fundamentals.',
    courseUrl: 'https://www.uniathena.com/certificate-in-entrepreneurship',
    instructor: 'UniAthena',
    institution: 'UniAthena',
    duration: 1800, // 6-8 weeks
    category: 'Business',
    subcategory: 'Entrepreneurship',
    difficulty: 'Beginner',
    tags: ['Entrepreneurship', 'Business Planning', 'Startup', 'Funding'],
    price: 100,
    rating: 4.7,
    reviewCount: 800,
    enrollmentCount: 3000,
    isVerified: true,
    isFeatured: false,
    sageRecommended: true,
    africanRelevance: 10,
    workContractCount: 30,
    hasCertificate: true,
    certificateType: 'Certificate',
  },

  // ===== LINKEDIN LEARNING =====
  {
    tenantId: 'system',
    platform: 'LINKEDIN_LEARNING' as const,
    externalId: 'react-essential',
    title: 'React.js Essential Training',
    description: 'Learn React fundamentals, components, hooks, and state management. Build modern web applications.',
    courseUrl: 'https://www.linkedin.com/learning/react-js-essential-training',
    instructor: 'Eve Porcello',
    institution: 'LinkedIn',
    duration: 600, // 10 hours
    category: 'Technology',
    subcategory: 'Web Development',
    difficulty: 'Intermediate',
    tags: ['React', 'JavaScript', 'Frontend', 'Components'],
    price: 29.99,
    rating: 4.7,
    reviewCount: 15000,
    enrollmentCount: 60000,
    isVerified: false,
    isFeatured: false,
    sageRecommended: false,
    africanRelevance: 8,
    workContractCount: 40,
    hasCertificate: true,
    certificateType: 'Completion Certificate',
  },
  {
    tenantId: 'system',
    platform: 'LINKEDIN_LEARNING' as const,
    externalId: 'python-essential',
    title: 'Python Essential Training',
    description: 'Master Python programming. Learn syntax, data structures, file handling, and object-oriented programming.',
    courseUrl: 'https://www.linkedin.com/learning/python-essential-training-2',
    instructor: 'Bill Weinman',
    institution: 'LinkedIn',
    duration: 720, // 12 hours
    category: 'Technology',
    subcategory: 'Programming',
    difficulty: 'Beginner',
    tags: ['Python', 'Programming', 'OOP', 'Data Structures'],
    price: 29.99,
    rating: 4.8,
    reviewCount: 25000,
    enrollmentCount: 100000,
    isVerified: false,
    isFeatured: false,
    sageRecommended: false,
    africanRelevance: 9,
    workContractCount: 55,
    hasCertificate: true,
    certificateType: 'Completion Certificate',
  },

  // ===== AWS SKILL BUILDER =====
  {
    tenantId: 'system',
    platform: 'AWS_SKILLBUILDER' as const,
    externalId: 'aws-cloud-practitioner',
    title: 'AWS Cloud Practitioner Essentials',
    description: 'Learn cloud computing fundamentals with AWS. Understand core services, pricing, and architecture.',
    courseUrl: 'https://aws.amazon.com/training/digital/aws-cloud-practitioner/',
    instructor: 'AWS',
    institution: 'Amazon Web Services',
    duration: 600, // 10 hours
    category: 'Technology',
    subcategory: 'Cloud Computing',
    difficulty: 'Beginner',
    tags: ['AWS', 'Cloud', 'Cloud Computing', 'Architecture'],
    price: 0,
    rating: 4.8,
    reviewCount: 40000,
    enrollmentCount: 200000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 9,
    workContractCount: 90,
    hasCertificate: true,
    certificateType: 'Certification',
  },
  {
    tenantId: 'system',
    platform: 'AWS_SKILLBUILDER' as const,
    externalId: 'aws-solutions-architect',
    title: 'AWS Solutions Architect - Associate Level',
    description: 'Prepare for the SAA-C03 exam. Learn to design distributed systems on AWS.',
    courseUrl: 'https://aws.amazon.com/training/digital/awssolutionsarchitect/',
    instructor: 'AWS',
    institution: 'Amazon Web Services',
    duration: 1800, // 30 hours
    category: 'Technology',
    subcategory: 'Cloud Architecture',
    difficulty: 'Intermediate',
    tags: ['AWS', 'Solutions Architect', 'Cloud Architecture', 'AWS Services'],
    price: 0,
    rating: 4.7,
    reviewCount: 30000,
    enrollmentCount: 150000,
    isVerified: true,
    isFeatured: true,
    sageRecommended: true,
    africanRelevance: 8,
    workContractCount: 120,
    hasCertificate: true,
    certificateType: 'Certification',
  },
];

async function main() {
  console.log('🌱 Seeding external courses...');

  for (const course of externalCourses) {
    try {
      await prisma.externalCourse.upsert({
        where: {
          platform_externalId: {
            platform: course.platform,
            externalId: course.externalId,
          },
        },
        update: {
          ...course,
          lastSynced: new Date(),
        },
        create: {
          ...course,
        },
      });
      console.log(`✓ Created: ${course.title} (${course.platform})`);
    } catch (error) {
      console.error(`✗ Error creating ${course.title}:`, error);
    }
  }

  console.log('✅ External courses seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
