import { Router } from "express";
import authRoutes from "./authRoutes.js";
import passwordResetRoutes from "./passwordResetRoutes.js";
import tenantsRoutes from "./tenantsRoutes.js";
import usersRoutes from "./usersRoutes.js";
import analyticsRoutes from "./analyticsRoutes.js";
import exportRoutes from "./exportRoutes.js";
import billingRoutes from "./billingRoutes.js";
import aiRoutes from "./aiRoutes.js";
import profileRoutes from "./profileRoutes.js";
import emailRoutes from "./emailRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import stripeRoutes from "./stripeRoutes.js";
import searchRoutes from "./searchRoutes.js";
import activityRoutes from "./activityRoutes.js";
import referralRoutes from "./referralRoutes.js";
import adminRoutes from "./adminRoutes.js";
import changelogRoutes from "./changelogRoutes.js";
import twoFactorRoutes from "./twoFactorRoutes.js";
import postRoutes from "./postRoutes.js";
import groupRoutes from "./groupRoutes.js";
import slackRoutes from "./slackRoutes.js";
import ssoRoutes from "./ssoRoutes.js";
import registryRoutes from "./registryRoutes.js";
import healthRoutes from "./healthRoutes.js";
import gdprRoutes from "./gdprRoutes.js";
import academyRoutes from "./academyRoutes.js";
import { authLimiter, postLimiter } from "../middleware/rateLimitMiddleware.js";

const router = Router();

router.use("/auth/login", authLimiter);
router.use("/auth/register", authLimiter);
router.use("/auth", authRoutes);
router.use("/auth", passwordResetRoutes);
router.use("/health", healthRoutes);
router.use("/tenants", tenantsRoutes);
router.use("/users", usersRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/export", exportRoutes);
router.use("/billing", billingRoutes);
router.use("/ai", aiRoutes);
router.use("/profile", profileRoutes);
router.use("/email", emailRoutes);
router.use("/notifications", notificationRoutes);
router.use("/stripe", stripeRoutes);
router.use("/search", searchRoutes);
router.use("/activity", activityRoutes);
router.use("/referral", referralRoutes);
router.use("/admin", adminRoutes);
router.use("/changelog", changelogRoutes);
router.use("/2fa", twoFactorRoutes);
router.use("/posts", postLimiter, postRoutes);
router.use("/groups", groupRoutes);
router.use("/gdpr", gdprRoutes);
router.use("/slack", slackRoutes);
router.use("/sso", ssoRoutes);
router.use("/registry", registryRoutes);
router.use("/academy", academyRoutes);

export default router;
