// Level II - AI-Present on Every Page
// Component: AIInsightBanner
// Purpose: Shows a 1-2 sentence insight generated by the layer's named AI supervisor

import { useState, useEffect } from "react";

interface AIInsightBannerProps {
  assistant: "aria" | "nova" | "sage" | "atlas" | "circuit" | "forge" | "nexus" | "herald" | "omega";
  page: string;
  userId?: string;
  context?: Record<string, unknown>;
}

interface InsightResponse {
  insight: string;
  assistant: string;
  timestamp: string;
}

const ASSISTANT_LABELS: Record<string, string> = {
  aria: "ARIA",
  nova: "NOVA",
  sage: "SAGE",
  atlas: "ATLAS",
  circuit: "CIRCUIT",
  forge: "FORGE",
  nexus: "NEXUS",
  herald: "HERALD",
  omega: "OMEGA",
};

const DEFAULT_INSIGHTS: Record<string, string> = {
  dashboard: "ARIA is analyzing your workspace. Check back for personalized insights.",
  community: "NOVA is learning your interests. Your first posts will unlock personalized recommendations.",
  academy: "SAGE is ready to guide your learning journey. Enroll in a course to begin.",
  market: "ATLAS is monitoring market trends. Set up your store to receive product insights.",
  work: "CIRCUIT is scanning for opportunities. Complete your profile to get matched with jobs.",
  intelligence: "FORGE is optimizing your AI experience. Try sending a message to get started.",
};

export default function AIInsightBanner({ assistant, page, userId, context }: AIInsightBannerProps) {
  const [insight, setInsight] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isDismissed, setIsDismissed] = useState(false);
  const [error, setError] = useState(false);

  useEffect(() => {
    // Check localStorage for dismissed state
    const dismissedKey = `ai_insight_dismissed_${page}_${new Date().toDateString()}`;
    if (localStorage.getItem(dismissedKey)) {
      setIsDismissed(true);
      setIsLoading(false);
      return;
    }

    const fetchInsight = async () => {
      try {
        // Try to fetch from API
        const response = await fetch("/api/v1/ai/page-insight", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            ...(userId ? { "X-User-ID": userId } : {}),
          },
          body: JSON.stringify({ assistant, page, context }),
        });

        if (response.ok) {
          const data: InsightResponse = await response.json();
          setInsight(data.insight);
        } else {
          // Fall back to default insight
          setInsight(DEFAULT_INSIGHTS[page] || "AI insight loading...");
        }
      } catch {
        // Fall back to default on network error
        setInsight(DEFAULT_INSIGHTS[page] || "AI is analyzing your activity...");
      } finally {
        setIsLoading(false);
      }
    };

    // Simulate network delay for UX
    const timer = setTimeout(fetchInsight, 800);

    return () => clearTimeout(timer);
  }, [assistant, page, userId, context]);

  const handleDismiss = () => {
    const dismissedKey = `ai_insight_dismissed_${page}_${new Date().toDateString()}`;
    localStorage.setItem(dismissedKey, "true");
    setIsDismissed(true);
  };

  if (isDismissed || error) {
    return null;
  }

  return (
    <div className="ai-insight-banner">
      <div className="ai-insight-label">
        <span className="ai-insight-icon">
          {assistant === "omega" ? "🧠" : 
           assistant === "nova" ? "👥" :
           assistant === "sage" ? "🎓" :
           assistant === "atlas" ? "🛒" :
           assistant === "circuit" ? "💼" :
           assistant === "forge" ? "🤖" :
           assistant === "nexus" ? "☁️" :
           assistant === "herald" ? "🧬" : "⬡"}
        </span>
        {ASSISTANT_LABELS[assistant] || assistant}
      </div>
      
      <div className="ai-insight-content">
        {isLoading ? (
          <div className="ai-insight-skeleton">
            <div className="skeleton-line" style={{ width: "70%" }} />
            <div className="skeleton-line" style={{ width: "45%" }} />
          </div>
        ) : (
          <p className="ai-insight-text">{insight}</p>
        )}
      </div>

      <button 
        className="ai-insight-dismiss" 
        onClick={handleDismiss}
        aria-label="Dismiss insight"
      >
        ×
      </button>

      <style>{`
        .ai-insight-banner {
          background: rgba(155, 111, 255, 0.06);
          border: 1px solid rgba(155, 111, 255, 0.15);
          border-left: 3px solid var(--purple);
          border-radius: 0 6px 6px 0;
          padding: 14px 18px;
          margin-bottom: 24px;
          display: flex;
          align-items: flex-start;
          gap: 14px;
          animation: fadeInUp 0.4s ease both;
        }

        .ai-insight-label {
          font-family: 'Space Mono', monospace;
          font-size: 8px;
          letter-spacing: 0.3em;
          text-transform: uppercase;
          color: var(--purple);
          white-space: nowrap;
          padding-top: 2px;
          display: flex;
          align-items: center;
          gap: 6px;
          flex-shrink: 0;
        }

        .ai-insight-icon {
          font-size: 14px;
        }

        .ai-insight-content {
          flex: 1;
          min-width: 0;
        }

        .ai-insight-text {
          font-size: 13.5px;
          color: var(--text);
          line-height: 1.6;
          font-family: 'Syne', sans-serif;
          margin: 0;
        }

        .ai-insight-skeleton {
          display: flex;
          flex-direction: column;
          gap: 6px;
        }

        .skeleton-line {
          height: 12px;
          background: linear-gradient(90deg, var(--border) 25%, var(--surface2) 50%, var(--border) 75%);
          background-size: 200% 100%;
          animation: shimmer 1.5s infinite;
          border-radius: 2px;
        }

        @keyframes shimmer {
          0% { background-position: 200% 0; }
          100% { background-position: -200% 0; }
        }

        .ai-insight-dismiss {
          background: none;
          border: none;
          color: var(--text-dim);
          font-size: 18px;
          cursor: pointer;
          padding: 0;
          line-height: 1;
          opacity: 0.6;
          transition: opacity 0.2s, color 0.2s;
          flex-shrink: 0;
        }

        .ai-insight-dismiss:hover {
          opacity: 1;
          color: var(--text);
        }

        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(12px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @media (max-width: 640px) {
          .ai-insight-banner {
            flex-wrap: wrap;
            padding: 12px 14px;
          }

          .ai-insight-label {
            width: 100%;
            margin-bottom: 8px;
          }

          .ai-insight-content {
            width: calc(100% - 30px);
          }

          .ai-insight-dismiss {
            position: absolute;
            top: 8px;
            right: 8px;
          }
        }
      `}</style>
    </div>
  );
}
